version: '3.4'

services:
  gateway-api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
  order-api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Order.API/Dockerfile
  customer-api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Customer.API/Dockerfile